# Aggregate Functions

In [1]:
from pyspark.sql import SparkSession

In [2]:
spark = SparkSession.builder.appName('Aggregate').getOrCreate()

In [5]:
df_pyspark = spark.read.csv('Food demand.csv',header=True,inferSchema=True)

In [6]:
df_pyspark.show()

+-------+----+---------+-------+--------------+----------+---------------------+-----------------+----------+
|     id|week|center_id|meal_id|checkout_price|base_price|emailer_for_promotion|homepage_featured|num_orders|
+-------+----+---------+-------+--------------+----------+---------------------+-----------------+----------+
|1000000|   3|      157|   2760|        233.83|    231.83|                    0|                0|       149|
|1000001| 100|      104|   2956|        486.03|    583.03|                    0|                0|       161|
|1000002| 143|       75|   1971|        328.86|    327.86|                    0|                0|       149|
|1000003|  41|       24|   2539|        145.53|    145.53|                    0|                0|       540|
|1000004|  45|       83|   2539|         95.06|    120.34|                    0|                0|       271|
|1000005| 101|       65|   1754|        291.03|    290.03|                    0|                0|       541|
|1000006| 107|      153|   2126|        533.53|    533.53|                    0|                0|        53|
|1000007|  11|       50|   1062|        160.11|    159.11|                    0|                0|       432|
|1000008| 114|       57|   1962|        467.54|    639.23|                    1|                1|       486|
|1000009|  68|       36|   1216|        406.43|    408.43|                    0|                0|        28|
|1000010|  10|       76|   2760|        243.53|    241.53|                    0|                0|       108|
|1000011|  18|      104|   2867|        618.86|    619.86|                    0|                0|        53|
|1000012|  33|       36|   2494|        256.08|     243.5|                    0|                1|        94|
|1000013| 140|       88|   1571|        485.03|    631.53|                    0|                0|        81|
|1000014| 105|       81|   2139|        290.03|    290.03|                    0|                0|        55|
|1000015| 112|       43|   2290|        286.15|    288.15|                    0|                0|      1863|
|1000016| 131|       77|   2290|        255.11|    257.11|                    0|                0|       418|
|1000017|   9|       80|   2826|        298.76|    298.76|                    0|                0|       771|
|1000018| 101|       92|   1445|        459.78|    709.13|                    0|                0|        27|
|1000019|  18|       52|   1311|        158.14|    158.14|                    0|                0|       742|
+-------+----+---------+-------+--------------+----------+---------------------+-----------------+----------+
only showing top 20 rows

In [8]:
df_pyspark.groupBy('emailer_for_promotion').sum().show()

+---------------------+----------+---------+--------------+------------+-------------------+-----------------+--------------------------+----------------------+---------------+
|emailer_for_promotion|   sum(id)|sum(week)|sum(center_id)|sum(meal_id)|sum(checkout_price)|  sum(base_price)|sum(emailer_for_promotion)|sum(homepage_featured)|sum(num_orders)|
+---------------------+----------+---------+--------------+------------+-------------------+-----------------+--------------------------+----------------------+---------------+
|                    1| 153159148|     9922|         13128|      316521|  51577.48999999995|68341.77999999998|                       153|                    80|          98074|
|                    0|1848025959|   140789|        150090|     3701716|  602700.4000000054|627255.9800000056|                         0|                   130|         418348|
+---------------------+----------+---------+--------------+------------+-------------------+-----------------+--------------------------+----------------------+---------------+

In [9]:
df_pyspark.groupBy('emailer_for_promotion').mean().show()

+---------------------+-----------------+-----------------+-----------------+------------------+-------------------+------------------+--------------------------+----------------------+-----------------+
|emailer_for_promotion|          avg(id)|        avg(week)|   avg(center_id)|      avg(meal_id)|avg(checkout_price)|   avg(base_price)|avg(emailer_for_promotion)|avg(homepage_featured)|  avg(num_orders)|
+---------------------+-----------------+-----------------+-----------------+------------------+-------------------+------------------+--------------------------+----------------------+-----------------+
|                    1|1001040.183006536|64.84967320261438|85.80392156862744| 2068.764705882353|  337.1077777777774|446.67830065359465|                       1.0|    0.5228758169934641|641.0065359477125|
|                    0|1001097.485915493| 76.2670639219935|81.30552546045504|2005.2632719393282| 326.48992416034963| 339.7919718309889|                       0.0|   0.07042253521126761|226.6240520043337|
+---------------------+-----------------+-----------------+-----------------+------------------+-------------------+------------------+--------------------------+----------------------+-----------------+

In [10]:
df_pyspark.groupBy('emailer_for_promotion').min().show()

+---------------------+-------+---------+--------------+------------+-------------------+---------------+--------------------------+----------------------+---------------+
|emailer_for_promotion|min(id)|min(week)|min(center_id)|min(meal_id)|min(checkout_price)|min(base_price)|min(emailer_for_promotion)|min(homepage_featured)|min(num_orders)|
+---------------------+-------+---------+--------------+------------+-------------------+---------------+--------------------------+----------------------+---------------+
|                    1|1000008|        1|            10|        1062|              92.15|          96.09|                         1|                     0|             14|
|                    0|1000000|        1|            10|        1062|              65.02|          93.12|                         0|                     0|             13|
+---------------------+-------+---------+--------------+------------+-------------------+---------------+--------------------------+----------------------+---------------+

In [11]:
df_pyspark.groupBy('emailer_for_promotion').max().show()

+---------------------+-------+---------+--------------+------------+-------------------+---------------+--------------------------+----------------------+---------------+
|emailer_for_promotion|max(id)|max(week)|max(center_id)|max(meal_id)|max(checkout_price)|max(base_price)|max(emailer_for_promotion)|max(homepage_featured)|max(num_orders)|
+---------------------+-------+---------+--------------+------------+-------------------+---------------+--------------------------+----------------------+---------------+
|                    1|1002145|      144|           186|        2867|             583.03|         765.33|                         1|                     1|          12137|
|                    0|1002181|      145|           186|        2956|             767.33|         767.33|                         0|                     1|           3605|
+---------------------+-------+---------+--------------+------------+-------------------+---------------+--------------------------+----------------------+---------------+

In [12]:
df_pyspark.groupBy('emailer_for_promotion').count().show()

+---------------------+-----+
|emailer_for_promotion|count|
+---------------------+-----+
|                    1|  153|
|                    0| 1846|
+---------------------+-----+

In [13]:
df_pyspark.agg({'checkout_price':'max'}).show()

+-------------------+
|max(checkout_price)|
+-------------------+
|             767.33|
+-------------------+